### ISSUE TITLE
Especificações 

### ISSUE THREAD

**Issue by alanqg** [alanqg/html-5_antigoCusoemVideo#1]
Essa é os arquivos estilizado do curso html-5 antigo do curso em vídeos.

**Comment by aqgoes79** [comment]
Os arquivos .php são os arquivos que são para o tema Wordpress ?

**Comment by alanqg** [comment]
> Os arquivos .php são os arquivos que são para o tema Wordpress?

Isso, para ter basta pegar todos os arquivos é color na pasta nome_do_site\wp-content\themes\nome_do_tema.
Todos os arquivos devem ser colada na pasta nome_do_tema (nome do tema deve ser da sua preferência.)

**Comment by alanqg** [comment]
Essa foi um isseus teste finalizando
