### ISSUE TITLE
Essa curso foi feito pela curso em vídeos 

### ISSUE THREAD

**Issue by aqgoes79** [alanqg/html-5_antigoCusoemVideo#2]
Gostaria de saber de esse curso é o curso antigo de html é css do curso em vídeo?
Grato!

**Comment by alanqg** [comment]
> Gostaria de saber de esse curso é o curso antigo de html é css do curso em vídeo?
> Grato!

Isso! Se não estou enganado esse foi o primeiro curso do curso em vídeo, mas sem dúvida esse foi o curso que me motivou a estudar programação web.
Para acessar o curso Html Antigo do curso em vídeo basta [clicar aqui](https://www.youtube.com/watch?v=epDCjksKMok&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o)
